[package]
name = "reth-node-metrics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
reth-db-api.workspace = true
reth-provider.workspace = true
reth-metrics.workspace = true
reth-tasks.workspace = true

metrics.workspace = true
metrics-exporter-prometheus.workspace = true
metrics-process.workspace = true
metrics-util.workspace = true

tokio.workspace = true

once_cell.workspace = true

jsonrpsee.workspace = true
http.workspace = true
tower.workspace = true

tracing.workspace = true
const_format.workspace = true
eyre.workspace = true

[target.'cfg(unix)'.dependencies]
tikv-jemalloc-ctl = { version = "0.5.0", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.16.0"

[lints]
workspace = true

[features]
jemalloc = ["dep:tikv-jemalloc-ctl"]


[build-dependencies]
vergen = { version = "8.0.0", features = ["build", "cargo", "git", "gitcl"] }
